### ISSUE TITLE
Infografía Realidad Aumentada

### ISSUE THREAD

**Issue by MaGuadalupeQuiroz** [SistemasTecTlaxiaco/infografia-MaGuadalupeQuiroz#1]
![Infografia Realidad Aumentada](https://user-images.githubusercontent.com/72761157/153736852-f808a7f4-7e6b-42d2-adbd-e55800e35b43.jpg)

**Comment by claudiasilvavenda** [comment]
La infografía cumple con lo que pide la rubrica.
la calif. es 20%.

**Comment by josealfredo79** [comment]
Bien hecho y revisado
