### ISSUE TITLE
Infografia

### ISSUE THREAD

**Issue by MaGuadalupeQuiroz** [SistemasTecTlaxiaco/infografia-MaGuadalupeQuiroz#2]
![Infografia Ingenieria de Requisitos](https://user-images.githubusercontent.com/72761157/110167787-db81b800-7dbb-11eb-8ef6-8751e5e11659.jpg)

**Comment by Gerardo-79** [comment]
Excelente infografía.  
Contiene todo  los aspectos de la rubrica.
Calificación 20/20

**Comment by josealfredo79** [comment]
Bien realizado y revisado.
